openapi: 3.0.0
info:
  title: USA Flights API
  description:
    "This API allows the user to obtain information and statistics flights\
    \ that occured in 2020, 2021 and 2022. It also allows users to forecast future\
    \ flights with this data. Plus, admins can add new flights, update flight information\
    \ and delete existing ones."
  version: 1.0.0
servers:
  - url: /
tags:
  - name: flights
    description: Obtain information about flights and get flight forecasts
  - name: airlines
    description: Obtain information about airlines and their reliability
  - name: admin
    description: Add a new flight and update or delete an existing one
paths:
  /flights/statistics:
    get:
      tags:
        - flights
      summary: Obtain statistics regarding flights
      description: "Obtain flight statistics, given certain criteria."
      operationId: get_flights_statistics
      parameters:
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: airline_code
          in: query
          description: Filter results by airlines
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: origin_airport_id
          in: query
          description: Filter results by the origin airport
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: dest_airport_id
          in: query
          description: Filter results by the destination airport
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: start_date
          in: query
          description: Filter results with a flight date after the given date
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: date
        - name: end_date
          in: query
          description: Filter results with a flight date before the given date
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: date
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200"
        "400":
          description: Invalid Parameters
      x-openapi-router-controller: swagger_server.controllers.flights_controller
  /flights/{flight-number}:
    get:
      tags:
        - flights
      summary: Obtain flight data by flight number
      description: Obtain flight data given a flight number
      operationId: get_flight_by_number
      parameters:
        - name: flight_number
          in: path
          description: Number of the flight to return
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Flight"
        "400":
          description: Invalid Flight Number
        "404":
          description: Flight Not Found
      x-openapi-router-controller: swagger_server.controllers.flights_controller
  /flights/forecast:
    get:
      tags:
        - flights
      summary: Obtain a forecast for a future flight
      description:
        "Obtain predictions for a future flight, given a date and other\
        \ details"
      operationId: get_flight_forecast
      parameters:
        - name: flight_date
          in: query
          description: Date for future flight
          required: true
          style: form
          explode: true
          schema:
            type: string
            format: date
        - name: airline_code
          in: query
          description: Airline for future flight
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: origin_airport_id
          in: query
          description: Origin airport for future flight
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: dest_airport_id
          in: query
          description: Destination airport for future flight
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: departure_time
          in: query
          description: Departure time for future flight
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: time
        - name: arrival_time
          in: query
          description: Arrival time for future flight
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: time
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightPrediction"
        "400":
          description: Invalid Parameters
      x-openapi-router-controller: swagger_server.controllers.flights_controller
  /airlines/{airline-code}:
    get:
      tags:
        - airlines
      summary: Obtain airline data by airline code
      description: Obtain airline data given an airline code
      operationId: get_airline_by_code
      parameters:
        - name: airline_code
          in: path
          description: Unique carrier code of the airline to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Airline"
        "400":
          description: Invalid Airline Code
        "404":
          description: Airline Not Found
      x-openapi-router-controller: swagger_server.controllers.airlines_controller
  /airlines/rank:
    get:
      tags:
        - airlines
      summary: Obtain airline ranks
      description:
        "Obtain airline ranks, given weights and specifications for calculating\
        \ it"
      operationId: get_airline_ranks
      parameters:
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: cancellation_weight
          in: query
          description: Weight of cancellations in calculating the airline rank
          required: false
          style: form
          explode: true
          schema:
            maximum: 100
            minimum: 0
            type: integer
            format: int32
        - name: diversion_weight
          in: query
          description: Weight of diversions in calculating the airline rank
          required: false
          style: form
          explode: true
          schema:
            maximum: 100
            minimum: 0
            type: integer
            format: int32
        - name: delay_weight
          in: query
          description: Weight of delays in calculating the airline rank
          required: false
          style: form
          explode: true
          schema:
            maximum: 100
            minimum: 0
            type: integer
            format: int32
        - name: airline_code
          in: query
          description: Rank the given airline
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: origin_airport_id
          in: query
          description: Rank airlines using flight data from this origin airport
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: dest_airport_id
          in: query
          description: Rank airlines using flight data from this destination airport
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
        - name: start_date
          in: query
          description: Rank airlines using flight data after the given date
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: date
        - name: end_date
          in: query
          description: Rank airlines using flight data before the given date
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: date
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AirlineRank"
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.airlines_controller
  /admin/flights:
    post:
      tags:
        - admin
      summary: Add a new flight
      description: The admin can add a new flight and its information
      operationId: post_flight
      requestBody:
        description: Add a new flight
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Flight"
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Flight"
                x-content-type: application/json
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.admin_controller
  /admin/flights/{flight-number}:
    put:
      tags:
        - admin
      summary: Update an existing flight
      description:
        The admin can update an existing flight's information by its flight
        number
      operationId: put_flight
      parameters:
        - name: flight_number
          in: query
          description: Number of the flight to update
          required: true
          style: form
          explode: false
          schema:
            type: integer
            format: int32
      requestBody:
        description: Update an existing flight
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Flight"
        required: true
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Flight"
                x-content-type: application/json
        "404":
          description: Flight not Found
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.admin_controller
    delete:
      tags:
        - admin
      summary: Delete an existing flight
      description: The admin can delete an existing flight by its flight number
      operationId: delete_flight
      parameters:
        - name: flight_number
          in: query
          description: Number of the flight to delete
          required: true
          style: form
          explode: false
          schema:
            type: integer
            format: int32
      responses:
        "204":
          description: Successful Deletion
        "404":
          description: Flight not Found
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.admin_controller
components:
  schemas:
    Flight:
      type: object
      properties:
        flightDate:
          type: string
          format: date
        flightNumber:
          type: integer
          format: int32
        flightDuration:
          type: integer
          format: int32
        cancelled:
          type: boolean
        diverted:
          type: boolean
        tailNumber:
          type: string
        airlineCode:
          type: string
        departure:
          $ref: "#/components/schemas/FlightLandOrDep"
        arrival:
          $ref: "#/components/schemas/FlightLandOrDep"
      example:
        diverted: true
        flightDate: 2000-01-23
        arrival: null
        tailNumber: tailNumber
        flightDuration: 6
        cancelled: true
        airlineCode: airlineCode
        departure:
          actual: 5
          delay: 2
          airportId: 1
          scheduled: 5
        flightNumber: 0
    Airline:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        iata:
          type: string
        icao:
          type: string
      example:
        code: code
        iata: iata
        name: name
        icao: icao
    AirlineRank:
      type: object
      properties:
        rankScore:
          maximum: 100
          minimum: 0
          type: integer
          format: int32
        airline:
          $ref: "#/components/schemas/Airline"
        statistics:
          $ref: "#/components/schemas/FlightsStatistics"
      example:
        rankScore: 8
        airline:
          code: code
          iata: iata
          name: name
          icao: icao
        statistics:
          total_flights: 0
          average_delay: 6.0274563
          max_delay: 1
          cancellation_percentage: 59.621338
          diversion_percentage: 56.373768
    FlightLandOrDep:
      type: object
      properties:
        airportId:
          type: integer
          format: int32
        scheduled:
          type: integer
          format: time
        actual:
          type: integer
          format: time
        delay:
          type: integer
          format: int32
      example:
        actual: 5
        delay: 2
        airportId: 1
        scheduled: 5
    FlightPrediction:
      type: object
      properties:
        cancellingProbability:
          maximum: 1
          minimum: 0
          type: number
          format: float
        divertingProbability:
          maximum: 1
          minimum: 0
          type: number
          format: float
        expectedDelay:
          type: integer
          format: int32
      example:
        divertingProbability: 0.6027456
        cancellingProbability: 0.08008282
        expectedDelay: 1
    FlightsStatistics:
      type: object
      properties:
        total_flights:
          type: integer
          format: int64
        average_delay:
          type: number
          format: float
        max_delay:
          type: integer
          format: int32
        cancellation_percentage:
          maximum: 100
          minimum: 0
          type: number
          format: float
        diversion_percentage:
          maximum: 100
          minimum: 0
          type: number
          format: float
      example:
        total_flights: 0
        average_delay: 6.0274563
        max_delay: 1
        cancellation_percentage: 59.621338
        diversion_percentage: 56.373768
    inline_response_200:
      type: object
      properties:
        statistics:
          $ref: "#/components/schemas/FlightsStatistics"
      example:
        statistics:
          total_flights: 0
          average_delay: 6.0274563
          max_delay: 1
          cancellation_percentage: 59.621338
          diversion_percentage: 56.373768
